from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from io import BytesIO
import os
from supabase import create_client
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm

from app.database import get_db
from app.middleware.auth import get_current_user, inspector_only
from app.models.inspection import Inspection
from app.models.hazard import Hazard
from app.models.corrective_action import CorrectiveAction
from app.models.report import Report

router = APIRouter()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

def get_supabase():
    return create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)


def generate_pdf(inspection, hazards) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph("MATTEL EHSS — SAFETY OBSERVATION REPORT", styles['Title']))
    story.append(Spacer(1, 0.5*cm))

    # Inspection info
    info_data = [
        ["Inspection ID:", str(inspection.id)],
        ["Location:", inspection.location or "-"],
        ["Area:", inspection.area or "-"],
        ["Status:", inspection.status],
        ["Date:", str(inspection.inspected_at)],
    ]
    info_table = Table(info_data, colWidths=[4*cm, 12*cm])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5*cm))

    # Hazards table
    story.append(Paragraph("Detected Hazards", styles['Heading2']))
    story.append(Spacer(1, 0.3*cm))

    hazard_data = [["#", "Category", "Risk Level", "Confidence", "Corrective Action", "Priority", "Due Date"]]
    for i, hazard in enumerate(hazards, 1):
        actions = hazard.corrective_actions
        action_desc = actions[0].action_description if actions else "-"
        priority = actions[0].priority if actions else "-"
        due_date = str(actions[0].due_date) if actions else "-"
        hazard_data.append([
            str(i),
            hazard.category,
            hazard.risk_level.upper(),
            f"{hazard.confidence_score:.0%}" if hazard.confidence_score else "-",
            action_desc[:60] + "..." if len(action_desc) > 60 else action_desc,
            priority.upper(),
            due_date,
        ])

    hazard_table = Table(hazard_data, colWidths=[1*cm, 3*cm, 2*cm, 2*cm, 4*cm, 2*cm, 2.5*cm])
    hazard_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#EEF4FB')]),
    ]))
    story.append(hazard_table)
    story.append(Spacer(1, 1*cm))

    # Footer
    story.append(Paragraph("Generated by SafetyHazard — Mattel EHSS AI System", styles['Normal']))

    doc.build(story)
    return buffer.getvalue()


# ── POST /reports/generate/{inspection_id} ─────────────────
@router.post("/generate/{inspection_id}", status_code=201)
async def generate_report(
    inspection_id: str,
    current_user=Depends(inspector_only),
    db: Session = Depends(get_db)
):
    inspection = db.query(Inspection).filter(
        Inspection.id == inspection_id
    ).first()

    if not inspection:
        raise HTTPException(status_code=404, detail="Inspection not found")

    if current_user.role == "inspector" and str(inspection.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to generate this report")

    hazards = db.query(Hazard).filter(
        Hazard.inspection_id == inspection.id
    ).all()

    # Generate PDF
    pdf_bytes = generate_pdf(inspection, hazards)
    filename = f"report_{inspection_id}.pdf"

    # Upload ke Supabase Storage pakai supabase-py client
    # (bukan httpx manual — key format baru Supabase tidak selalu
    # bisa dipakai langsung di header Authorization: Bearer)
    supabase = get_supabase()
    try:
        supabase.storage.from_("reports").upload(
            path=filename,
            file=pdf_bytes,
            file_options={"content-type": "application/pdf", "upsert": "true"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to upload PDF report: {str(e)}")

    pdf_url = f"{SUPABASE_URL}/storage/v1/object/public/reports/{filename}"

    # Simpan report ke DB
    report = Report(
        inspection_id=inspection.id,
        pdf_url=pdf_url,
        generated_by=current_user.id
    )
    db.add(report)

    inspection.status = "reported"
    db.commit()
    db.refresh(report)

    return {
        "report_id": str(report.id),
        "pdf_url": pdf_url,
        "generated_at": str(report.generated_at)
    }


# ── GET /reports/{id}/download ─────────────────────────────
@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    report = db.query(Report).filter(Report.id == report_id).first()

    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    filename = f"report_{report.inspection_id}.pdf"

    # Fetch PDF dari Supabase Storage pakai supabase-py client
    supabase = get_supabase()
    try:
        pdf_bytes = supabase.storage.from_("reports").download(filename)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"PDF file not found: {str(e)}")

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=report_{report_id}.pdf"}
    )
