from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from io import BytesIO
import os
from supabase import create_client
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm

from app.database import get_db
from app.middleware.auth import get_current_user, inspector_only
from app.models.inspection import Inspection
from app.models.hazard import Hazard
from app.models.corrective_action import CorrectiveAction
from app.models.report import Report
from app.models.user import User
from app.services import email_service

router = APIRouter()

# Urutan keparahan untuk menentukan risk tertinggi sebuah inspeksi.
_RISK_ORDER = {"critical": 4, "high": 3, "medium": 2, "low": 1}


def _overall_risk(hazards) -> str:
    """Risk level tertinggi dari sekumpulan hazard (default 'low')."""
    best = "low"
    for h in hazards:
        if _RISK_ORDER.get(h.risk_level, 0) > _RISK_ORDER.get(best, 0):
            best = h.risk_level
    return best

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

def get_supabase():
    return create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)


def generate_pdf(inspection, hazards) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph("MATTEL EHSS — SAFETY OBSERVATION REPORT", styles['Title']))
    story.append(Spacer(1, 0.5*cm))

    # Inspection info
    info_data = [
        ["Inspection ID:", str(inspection.id)],
        ["Location:", inspection.location or "-"],
        ["Area:", inspection.area or "-"],
        ["Status:", inspection.status],
        ["Date:", str(inspection.inspected_at)],
    ]
    info_table = Table(info_data, colWidths=[4*cm, 12*cm])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5*cm))

    # Hazards table
    story.append(Paragraph("Detected Hazards", styles['Heading2']))
    story.append(Spacer(1, 0.3*cm))

    if not hazards:
        # No hazards detected
        story.append(Paragraph("No hazards detected — Area is safe", styles['Normal']))
        story.append(Spacer(1, 1*cm))
    else:
        hazard_data = [["#", "Category", "Risk Level", "Confidence", "Corrective Action", "Priority", "Due Date"]]
        for i, hazard in enumerate(hazards, 1):
            actions = hazard.corrective_actions
            action_desc = actions[0].action_description if actions else "-"
            priority = actions[0].priority if actions else "-"
            due_date = str(actions[0].due_date) if actions else "-"
            hazard_data.append([
                str(i),
                hazard.category,
                hazard.risk_level.upper(),
                f"{hazard.confidence_score:.0%}" if hazard.confidence_score else "-",
                action_desc[:60] + "..." if len(action_desc) > 60 else action_desc,
                priority.upper(),
                due_date,
            ])

        hazard_table = Table(hazard_data, colWidths=[1*cm, 3*cm, 2*cm, 2*cm, 4*cm, 2*cm, 2.5*cm])
        hazard_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 4),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#EEF4FB')]),
        ]))
        story.append(hazard_table)
        story.append(Spacer(1, 1*cm))

    # Footer
    story.append(Paragraph("Generated by SafetyVision — Mattel EHSS AI System", styles['Normal']))

    doc.build(story)
    return buffer.getvalue()


# ── POST /reports/generate/{inspection_id} ─────────────────
@router.post("/generate/{inspection_id}", status_code=201)
async def generate_report(
    inspection_id: str,
    current_user=Depends(inspector_only),
    db: Session = Depends(get_db)
):
    inspection = db.query(Inspection).filter(
        Inspection.id == inspection_id
    ).first()

    if not inspection:
        raise HTTPException(status_code=404, detail="Inspection not found")

    if current_user.role == "inspector" and str(inspection.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to generate this report")

    # Query hazards with corrective_actions eagerly loaded
    hazards = db.query(Hazard).filter(
        Hazard.inspection_id == inspection.id
    ).all()
    
    # Load corrective_actions for each hazard
    for hazard in hazards:
        hazard.corrective_actions = db.query(CorrectiveAction).filter(
            CorrectiveAction.hazard_id == hazard.id
        ).all()

    # Generate PDF
    pdf_bytes = generate_pdf(inspection, hazards)
    filename = f"report_{inspection_id}.pdf"

    # Upload ke Supabase Storage pakai supabase-py client
    # (bukan httpx manual — key format baru Supabase tidak selalu
    # bisa dipakai langsung di header Authorization: Bearer)
    supabase = get_supabase()
    try:
        supabase.storage.from_("reports").upload(
            path=filename,
            file=pdf_bytes,
            file_options={"content-type": "application/pdf", "upsert": "true"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to upload PDF report: {str(e)}")

    pdf_url = f"{SUPABASE_URL}/storage/v1/object/public/reports/{filename}"

    # Simpan report ke DB
    report = Report(
        inspection_id=inspection.id,
        pdf_url=pdf_url,
        generated_by=current_user.id
    )
    db.add(report)

    inspection.status = "reported"
    db.commit()
    db.refresh(report)

    # Notifikasi email ke semua manager/admin bahwa ada report baru siap
    # direview. Non-fatal: gagal kirim email tidak boleh menggagalkan
    # response report yang sudah berhasil dibuat.
    try:
        recipients = db.query(User).filter(
            User.role.in_(["manager", "admin"]),
            User.status == "active"
        ).all()
        for recipient in recipients:
            email_service.send_report_ready(
                recipient.email,
                current_user.name,
                inspection.location,
                _overall_risk(hazards),
                len(hazards),
                str(inspection.id),
            )
    except Exception as e:
        print(f"[EMAIL ERROR] Failed to send report-ready email: {e}")

    return {
        "report_id": str(report.id),
        "pdf_url": pdf_url,
        "generated_at": str(report.generated_at)
    }


# ── GET /reports/{id}/download ─────────────────────────────
@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    report = db.query(Report).filter(Report.id == report_id).first()

    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    filename = f"report_{report.inspection_id}.pdf"

    # Fetch PDF dari Supabase Storage pakai supabase-py client
    supabase = get_supabase()
    try:
        pdf_bytes = supabase.storage.from_("reports").download(filename)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"PDF file not found: {str(e)}")

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=report_{report_id}.pdf"}
    )


# ── DELETE /reports/{report_id} ────────────────────────────
@router.delete("/{report_id}")
async def delete_report(
    report_id: str,
    current_user=Depends(inspector_only),
    db: Session = Depends(get_db)
):
    report = db.query(Report).filter(Report.id == report_id).first()
    
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    
    # Verify ownership: check if the inspection belongs to current_user
    inspection = db.query(Inspection).filter(
        Inspection.id == report.inspection_id
    ).first()
    
    if not inspection or str(inspection.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to delete this report")
    
    # Delete report from database
    db.delete(report)
    db.commit()
    
    return {"message": "Report deleted successfully"}


# ── GET /reports/list ──────────────────────────────────────
@router.get("/list")
def list_reports(
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Daftar inspeksi yang sudah dianalisa (untuk tabel Reports).
    Inspector hanya melihat miliknya; manager/admin melihat semua.
    Tiap baris: tanggal, lokasi, inspector, status, risk tertinggi,
    jumlah hazard, dan label hazard.
    """
    query = db.query(Inspection).filter(
        Inspection.status.in_(["analyzed", "reported"])
    )
    if current_user.role == "inspector":
        query = query.filter(Inspection.user_id == current_user.id)

    inspections = query.order_by(Inspection.created_at.desc()).all()

    # Peta user_id → nama inspector (hindari query N+1).
    user_ids = {i.user_id for i in inspections}
    users = db.query(User).filter(User.id.in_(user_ids)).all() if user_ids else []
    name_map = {str(u.id): u.name for u in users}

    # Cek report yang sudah tergenerate untuk tombol download.
    report_map = {}
    for r in db.query(Report).all():
        # simpan report terbaru per inspection
        report_map[str(r.inspection_id)] = str(r.id)

    rows = []
    for insp in inspections:
        hazards = db.query(Hazard).filter(Hazard.inspection_id == insp.id).all()
        rows.append({
            "id": str(insp.id),
            "report_id": report_map.get(str(insp.id)),
            "date": str(insp.inspected_at)[:10] if insp.inspected_at else "",
            "location": insp.location,
            "area": insp.area,
            "inspector": name_map.get(str(insp.user_id), "-"),
            "status": insp.status,
            "risk": _overall_risk(hazards),
            "issues": len(hazards),
            "hazards": [h.category for h in hazards],
        })

    return rows


# ── GET /reports/detail/{inspection_id} ────────────────────
@router.get("/detail/{inspection_id}")
def report_detail(
    inspection_id: str,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Detail satu inspeksi + hazard + corrective action (untuk modal Reports)."""
    inspection = db.query(Inspection).filter(
        Inspection.id == inspection_id
    ).first()
    if not inspection:
        raise HTTPException(status_code=404, detail="Inspection not found")

    if current_user.role == "inspector" and str(inspection.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Access denied")

    inspector = db.query(User).filter(User.id == inspection.user_id).first()
    hazards = db.query(Hazard).filter(Hazard.inspection_id == inspection.id).all()

    report = db.query(Report).filter(
        Report.inspection_id == inspection.id
    ).order_by(Report.generated_at.desc()).first()

    hazard_list = []
    for h in hazards:
        actions = db.query(CorrectiveAction).filter(
            CorrectiveAction.hazard_id == h.id
        ).all()
        hazard_list.append({
            "id": str(h.id),
            "category": h.category,
            "risk_level": h.risk_level,
            "confidence_score": h.confidence_score,
            "yolo_label": h.yolo_label,
            "corrective_actions": [
                {
                    "action_description": a.action_description,
                    "priority": a.priority,
                    "due_date": str(a.due_date),
                    "action_status": a.action_status,
                }
                for a in actions
            ],
        })

    return {
        "id": str(inspection.id),
        "report_id": str(report.id) if report else None,
        "date": str(inspection.inspected_at)[:10] if inspection.inspected_at else "",
        "location": inspection.location,
        "area": inspection.area,
        "image_url": inspection.image_url,
        "inspector": inspector.name if inspector else "-",
        "status": inspection.status,
        "risk": _overall_risk(hazards),
        "issues": len(hazards),
        "hazards": hazard_list,
    }
